print('***CONSECUTIVOS***')
n1 = int(input('\nDigite o 1º valor: '))
n2 = int(input('Digite o 2º valor: '))
print('O consecutivo de {} é {}'.format(n1, (n1 + 1)))
print('O consecutivo de {} é {}'.format(n2, (n2 + 1)))